Repository 5ire-tech/5ireChain, pull requests merged in 2024-05, with the labels that each got.

#115 Update latest chain spec for new thunder GA
  node/src/chain_spec/thunder_chain_spec.rs
  runtime/firechain-qa-runtime/src/lib.rs
  runtime/firechain-thunder-runtime/src/constants.rs
  runtime/firechain-thunder-runtime/src/lib.rs
  specs/5ire-thunder-chain-spec-raw.json
  specs/5ire-thunder-chain-spec.json
Labels: P2-Simulate

#117 inflation removed and total supply constant
  Cargo.lock
  Cargo.toml
  frame/babe/Cargo.toml
  frame/grandpa/Cargo.toml
  frame/im-online/Cargo.toml
  frame/reward/Cargo.toml
  frame/reward/src/lib.rs
  frame/reward/src/mock.rs
  frame/reward/src/tests.rs
  frame/session/benchmarking/Cargo.toml
  frame/staking/Cargo.toml
  frame/staking/reward-curve/Cargo.toml
  frame/staking/reward-curve/src/lib.rs
  frame/staking/reward-curve/src/log.rs
  frame/staking/reward-curve/tests/test.rs
  frame/staking/reward-fn/Cargo.toml
  frame/staking/reward-fn/src/lib.rs
  frame/staking/reward-fn/tests/test.rs
  frame/staking/src/lib.rs
  frame/staking/src/pallet/impls.rs
  frame/staking/src/pallet/mod.rs
  node/src/chain_spec/mainnet_chain_spec.rs
  node/src/chain_spec/qa_chain_spec.rs
  node/src/chain_spec/thunder_chain_spec.rs
  runtime/firechain-mainnet-runtime/Cargo.toml
  runtime/firechain-mainnet-runtime/src/lib.rs
  runtime/firechain-qa-runtime/Cargo.toml
  runtime/firechain-qa-runtime/src/lib.rs
  runtime/firechain-thunder-runtime/Cargo.toml
  runtime/firechain-thunder-runtime/src/lib.rs
Labels: enhancement, P2-Simulate, P3-InProgress

#129 fixed evm to native swap for low balance
  Cargo.lock
  frame/evm/src/lib.rs
  runtime/firechain-qa-runtime/Cargo.toml
  runtime/firechain-qa-runtime/src/lib.rs
  runtime/firechain-thunder-runtime/Cargo.toml
  runtime/firechain-thunder-runtime/src/lib.rs
Labels: runtime upgrade, P2-Simulate

#122 feat: add tests reward pallet
  Cargo.lock
  frame/reward/Cargo.toml
  frame/reward/src/mock.rs
  frame/reward/src/tests.rs
  runtime/firechain-thunder-runtime/src/lib.rs
Labels: bug, P3-InProgress

#140 feat: fix evm gas tests with binary search estimate gas
  integration-test-suite/tests/evmGas.test.ts
Labels: bug

#142 feat: update docs for command GA and new feature
  README.md
  docker/README.md
  docs/README.md
Labels: documentation
